Daily backup 2026-04-17 17:26:20 +0800

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -399,6 +399,7 @@ install_linux_packages() {
   local package_file=""
   local package_name
   local updated=0
+  local install_failed=0
 
   if [[ "$(id -u)" -ne 0 ]] && ! need_cmd sudo; then
     warn "sudo is unavailable; skipped Linux system package installation"
@@ -443,6 +444,7 @@ install_linux_packages() {
         if ! run_as_root apt-get install -y "$package_name"; then
           warn "failed to install package via apt: $package_name"
           record_status "linux package" "failed" "$package_name"
+          install_failed=1
         else
           record_status "linux package" "installed" "$package_name"
         fi
@@ -451,6 +453,7 @@ install_linux_packages() {
         if ! run_as_root dnf install -y "$package_name"; then
           warn "failed to install package via dnf: $package_name"
           record_status "linux package" "failed" "$package_name"
+          install_failed=1
         else
           record_status "linux package" "installed" "$package_name"
         fi
@@ -467,6 +470,7 @@ install_linux_packages() {
         if ! run_as_root pacman -S --noconfirm --needed "$package_name"; then
           warn "failed to install package via pacman: $package_name"
           record_status "linux package" "failed" "$package_name"
+          install_failed=1
         else
           record_status "linux package" "installed" "$package_name"
         fi
@@ -474,7 +478,11 @@ install_linux_packages() {
     esac
   done
 
-  record_status "system packages" "installed" "$manager"
+  if [[ "$install_failed" -eq 1 ]]; then
+    record_status "system packages" "failed" "$manager"
+  else
+    record_status "system packages" "installed" "$manager"
+  fi
 }
 
 bootstrap_system_packages() {
@@ -618,13 +626,30 @@ verify_alternates() {
 
 bootstrap_zsh_runtime() {
   local zsh_custom="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
+  local clone_failed=0
 
-  ensure_git_checkout "oh-my-zsh" "https://github.com/ohmyzsh/ohmyzsh.git" "$HOME/.oh-my-zsh"
-  ensure_git_checkout "powerlevel10k" "https://github.com/romkatv/powerlevel10k.git" "$zsh_custom/themes/powerlevel10k"
-  ensure_git_checkout "zsh-autosuggestions" "https://github.com/zsh-users/zsh-autosuggestions" "$zsh_custom/plugins/zsh-autosuggestions"
-  ensure_git_checkout "fast-syntax-highlighting" "https://github.com/zdharma-continuum/fast-syntax-highlighting.git" "$zsh_custom/plugins/fast-syntax-highlighting"
-  ensure_git_checkout "zsh-syntax-highlighting" "https://github.com/zsh-users/zsh-syntax-highlighting.git" "$zsh_custom/plugins/zsh-syntax-highlighting"
-  ensure_git_checkout "fzf-tab" "https://github.com/Aloxaf/fzf-tab" "$zsh_custom/plugins/fzf-tab"
+  if ! ensure_git_checkout "oh-my-zsh" "https://github.com/ohmyzsh/ohmyzsh.git" "$HOME/.oh-my-zsh"; then
+    clone_failed=1
+  fi
+  if ! ensure_git_checkout "powerlevel10k" "https://github.com/romkatv/powerlevel10k.git" "$zsh_custom/themes/powerlevel10k"; then
+    clone_failed=1
+  fi
+  if ! ensure_git_checkout "zsh-autosuggestions" "https://github.com/zsh-users/zsh-autosuggestions" "$zsh_custom/plugins/zsh-autosuggestions"; then
+    clone_failed=1
+  fi
+  if ! ensure_git_checkout "fast-syntax-highlighting" "https://github.com/zdharma-continuum/fast-syntax-highlighting.git" "$zsh_custom/plugins/fast-syntax-highlighting"; then
+    clone_failed=1
+  fi
+  if ! ensure_git_checkout "zsh-syntax-highlighting" "https://github.com/zsh-users/zsh-syntax-highlighting.git" "$zsh_custom/plugins/zsh-syntax-highlighting"; then
+    clone_failed=1
+  fi
+  if ! ensure_git_checkout "fzf-tab" "https://github.com/Aloxaf/fzf-tab" "$zsh_custom/plugins/fzf-tab"; then
+    clone_failed=1
+  fi
+
+  if [[ "$clone_failed" -eq 1 ]]; then
+    warn "one or more zsh runtime repositories failed to install; bootstrap continued"
+  fi
 }
 
 bootstrap_tmux() {
